sudo: required
services:
  - docker

after_success:
  - docker build -t ashrafsyed77/multi-client ./client
  - docker build -t ashrafsyed77/multi-nginx ./nginx
  - docker build -t ashrafsyed77/multi-server ./server
  - docker build -t ashrafsyed77/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push ashrafsyed77/multi-client
  - docker push ashrafsyed77/multi-nginx
  - docker push ashrafsyed77/multi-server
  - docker push ashrafsyed77/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-ap-south-1-713175488066
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY


